spring:
  application:
    name: ipd-dashboard-backend
  batch:
    initialize-schema: always
  datasource:
    schema: classpath:schema.sql # Schema did not get run by default and hence schema is added
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  logging:
    level:
      org.springframework.batch: DEBUG
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.jdbc.datasource.init: DEBUG
